pipeline {
  agent any

  stages {

    stage('Clone') {
      steps {
        echo 'Cloning Repository'
      }
    }

    stage('Build') {
      steps {
        echo 'Building Docker Image'
      }
    }

    stage('Deploy') {
      steps {
        echo 'Deploying Application'
      }
    }

  }
}
